name: Auto-Update FFlags
on:
  schedule:
    - cron: '* * * * *'
jobs:
  api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.sshprivate }}
      - name: Install simple-git
        run: npm i simple-git
      - name: Set git email
        run: git config user.email ${{ secrets.gitemail }}
      - name: Set git user
        run: git config user.name ${{ secrets.gituser }}
      - name: Run nodejs file
        run: node ./workflow-files/update
