name: Auto-Update FFlags
on:
  schedule:
    - cron: '* * * * *'
jobs:
  update-fflags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.sshprivate }}
      - name: Set git email
        run: git config --global user.email ${{ secrets.gitemail }}
      - name: Set git user
        run: git config --global user.name ${{ secrets.gituser }}
      - name: Clone repo
        run: git clone https://github.com/fheahdythdr/rco-but-it-uses-different-fflags
      - name: Run nodejs file
        id: update_fflags
        run: node ./workflow-files/update
      - name: Add changed file, commit and push to repo
        continue-on-error: true
        run: |
          git add /home/runner/work/rco-but-it-uses-different-fflags/rco-but-it-uses-different-fflags/ClientAppSettings.json
          git commit -a -m "Updated FFlags"
          git push origin main
